name: strandscape_env
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python
  - dash
  - dash-bootstrap-components
  - pandas
  - pika
  - fastapi
  - requests
  - yaml
  - pip
  - rabbitmq-server
  - uvicorn
  - dash-auth
  - httpx
  - pip:
      - dash-iconify
      - dash-ag-grid
      - dash-mantine-components
