# Data location
data:
  genecore_data_folder: "/g/korbel/STOCKS/Data/Assay/sequencing/2023"
  genecore_data_folder_old: "/g/korbel/shared/genecore"
  complete_data_folder: "/scratch/tweber/DATA/MC_DATA/STOCKS"
  # complete_data_folder: "/scratch/tweber/DATA/MC_DATA/STOCKS_DEV"
  # complete_data_folder: "/scratch/tweber/DATA/MC_DATA/STOCKS/Sequencing/StrandSeq"
  # data_folder: "/Users/tweber/Gits/belvedere/data"
  data_folder: "/g/korbel/WORKFLOW_RESULTS"
  # data_folder: "/g/korbel/weber/TMP/WORKFLOW_RESULTS_DEV"
  json_data_backup: "/scratch/tweber/TMP/data.json"
  rabbitmq:
    exchange: status_exchange
    queue: my_queue
    routing_key: latest_status

rabbitmq_general_settings:
  hostname: localhost

# panoptes configuration
panoptes:
  url: "http://127.0.0.1:8058"
  json_status_backup: "/scratch/tweber/TMP/status.json"
  rabbitmq:
    exchange: data
    queue: data_queue
    routing_key: latest_data
    hostname: localhost

# FastAPI configuration
fastapi:
  # host: "0.0.0.0"
  # host_docker: "fastapi-backend"
  host: "seneca.embl.de"
  port: 8059

# Dash configuration
dash:
  # host: "0.0.0.0"
  host: "seneca.embl.de"
  port: 8060

# Snakemake configuration
snakemake:
  binary: "/g/korbel2/weber/miniconda3/envs/snakemake_panoptesfix/bin/snakemake"
  # binary: "/Users/tweber/miniconda3/envs/snakemake_latest/bin"
  # repository_location: "/Users/tweber/Gits/snakemake_logs_dev"
  repository_location: "/g/korbel2/weber/workspace/mosaicatcher-update"

watchdog:
  # logs_folder: "/Users/tweber/Gits/snakemake_logs_dev/watchdog/logs"
  logs_folder: "/g/korbel2/weber/workspace/mosaicatcher-update/watchdog/logs"
