# Data location
data:
  genecore_data_folder : "/g/korbel/STOCKS/Sequencing"
  complete_data_folder : "/scratch/tweber/DATA/MC_DATA/STOCKS/Sequencing/StrandSeq"
  data_folder : "/Users/tweber/Gits/belvedere/data"
  json_data_backup : "data.json"
  rabbitmq:
    exchange: status_exchange
    queue: my_queue
    routing_key: latest_status


# Wf Status
panoptes:
  url: "http://127.0.0.1:8058"
  json_status_backup : "status.json"
  rabbitmq:
    exchange: data
    queue: data_queue
    routing_key: latest_data

fastapi:
  host: "localhost"
  # host: "seneca.embl.de"
  port: 8059

dash:
  host: "localhost"
  # host: "seneca.embl.de"
  port: 8060