# Data location
data:
  data_folder : "/Users/tweber/Gits/belvedere/data"
  json_data_backup : "data.json"
  rabbitmq:
    exchange: status_exchange
    queue: my_queue
    routing_key: latest_status


# Wf Status
panoptes:
  json_status_backup : "status.json"
  rabbitmq:
    exchange: data
    queue: data_queue
    routing_key: latest_data
