# Data location
data:
  data_folder : "/Users/tweber/Gits/belvedere/data"
  json_data_backup : "data.json"
  rabbitmq:
    exchange: status_exchange
    queue: my_queue
    routing_key: latest_status


# Wf Status
panoptes:
  url: "http://127.0.0.1:8058"
  json_status_backup : "status.json"
  rabbitmq:
    exchange: data
    queue: data_queue
    routing_key: latest_data

fastapi:
  host: "http://localhost"
  # host: "http://seneca.embl.de"
  port: 8059

dash:
  host: "http://localhost"
  # host: "http://seneca.embl.de"
  port: 8060