apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: panoptes
  name: panoptes
  namespace: tenant-panoptes-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: panoptes
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: panoptes
    spec:
      containers:
        - args:
            - panoptes
            - -v
            - --port
            - "8058"
          image: quay.io/biocontainers/panoptes-ui:0.2.3--pyh7cba7a3_0
          name: panoptes
          imagePullPolicy: Always  # Add this line
          ports:
            - containerPort: 8058
          resources:
            requests:
              cpu: "500m"  # Example CPU request
              memory: "256Mi"  # Example memory request
            limits:
              cpu: "1"  # Example CPU limit
              memory: "512Mi"  # Example memory limit

          volumeMounts:
            - mountPath: /data
              name: panoptes-claim0
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: panoptes-claim0
          persistentVolumeClaim:
            claimName: panoptes-claim0
status: {}
